 <-ERROR-> main.cpp:35 : (SDL_main) Exception de test
